### ISSUE TITLE
Pointer subtraction might be undefined

### ISSUE THREAD

**Issue by DurandA** [wolfSSL/wolfBoot#83]
I stumbled upon a pointer subtraction:
https://github.com/wolfSSL/wolfBoot/blob/9fc82ac9f14f5189c157e4ab9bb46facfa9b8aed/src/image.c#L493

Is it ok to measure an offset like that? C11 ([N1570](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf)) states that the behaviour is undefined when not pointing to an array:

> **6.5.6 Additive operators**
> ....
> <sup>9</sup> When two pointers are subtracted, both ***shall point to elements of the same array object, or one past the last element of the array object***; the result is the difference of the subscripts of the two array elements.

**Comment by danielinux** [comment]
I think this is not an issue because:

- The pointers are both `uint8_t`, with `sizeof(uint8_t) = 1` -> no pointer arith required by the compiler
- The result is always positive and small by design (`end_sha` is always _after_ `p`) -> it's always representable whatever the type of `ptrdiff_t` on the target
